sudo: required

language: go

services:
  - docker

script:
- docker build --target build-env -t exporter-merger --no-cache .
- >
  docker run
  --name exporter-merger
  --entrypoint "sh"
  -e CGO_ENABLED=0
  --workdir "/go/src/github.com/rebuy-de/exporter-merger"
  exporter-merger
  -euxc "make xc && mkdir releases && mv exporter-merger-* releases"
- docker cp -L exporter-merger:/go/src/github.com/rebuy-de/exporter-merger/releases ./releases
- ls -l *

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: releases/*
  skip_cleanup: true
  on:
    repo: rebuy-de/exporter-merger
    tags: true

