# -*- yaml -*-
version: 2.1
orbs:
  go-module: timakin/go-module@0.3.0
  sixrs-gke: sixriversystems/sixrs-gke@2.1.3

jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: Fix Path
          command: export PATH=$PATH:$GOROOT/bin
      - run:
          name: staticcheck
          command: go get honnef.co/go/tools/cmd/staticcheck
      - run:
          name: golint
          command: go get golang.org/x/lint/golint
      - run: go get -v -d ./...
      - run: go build ./...
      - run: make test
      - sixrs-gke/run-release
      - persist_to_workspace:
          root: ./
          paths:
            - .version
  docker-publish:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - sixrs-gke/docker-login
      - sixrs-gke/build-and-publish

workflows:
  build_and_release:
    jobs:
      - build:
          context: 6rs-circle
      - docker-publish:
          context: 6rs-circle
          requires:
            - build
